---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
name: SE3nv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.17
  - pip
  - pip:
    - hydra-core==1.3.2
    - pyrsistent==0.20.0
    - e3nn==0.3.3
    - wandb==0.12.0
    - pynvml==11.0.0
    - git+https://github.com/NVIDIA/dllogger#egg=dllogger
    - decorator==5.1.0
    - opt-einsum==3.4.0
    - opt-einsum-fx==0.1.4
    - scipy==1.13.1
    - pandas>=2.0.0
    - pydantic>=2.0.0
