---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
name: SE3nv
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.9.17
  - pytorch::pytorch=2.4.0=py3.9_cuda12.4_cudnn9.1.0_0
  - pytorch::torchvision=0.19.0
  - pytorch::torchaudio=2.4.0
  - pytorch::pytorch-cuda=12.4
  - pytorch::torchdata=0.8.0
  - nvidia::cuda-toolkit=12.4
  - pip
  - pip:
    - https://data.dgl.ai/wheels/torch-2.4/cu124/dgl-2.4.0%2Bcu124-cp39-cp39-manylinux1_x86_64.whl
    - hydra-core==1.3.2
    - pyrsistent==0.20.0
    - e3nn==0.3.3
    - wandb==0.12.0
    - pynvml==11.0.0
    - git+https://github.com/NVIDIA/dllogger#egg=dllogger
    - decorator==5.1.0
    - opt-einsum==3.4.0
    - opt-einsum-fx==0.1.4
    - scipy==1.13.1
    - pandas>=2.0.0
    - pydantic>=2.0.0
